version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: robosats_web_1
      APP_PORT: 12596

  web:
    image: recksato/robosats-client:v0.7.0-alpha@sha256:fcb8045d5da4a87865e2aca78fb90a37af110d5e069107051aafa33d95301331
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}