version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: robosats_web_1
      APP_PORT: 12596

  web:
    image: recksato/robosats-client:v0.7.0-alpha@sha256:28ae9e1de541a563cfd7555b9b182c32918eff9860c0475b37910f925e8e1302
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}